micronaut:
  application:
    name: kotlin-micronaut-example
  server:
    netty:
      access-logger:
        enabled: true

rabbitmq:
  queues:
    order-completed: orders.completed

webhooks:
  order-completed:
    url: ${ORDER_COMPLETED_WEBHOOK_URL}
