micronaut:
  application:
    name: kotlin-micronaut-example

mongodb:
  uri: ${MONGODB_URI:`mongodb://localhost:27017/orders`}

rabbitmq:
  uri: ${RABBITMQ_URI:`amqp://guest:guest@localhost:5672/%2f`}
