micronaut:
  application:
    name: kotlin-micronaut-example
  server:
    netty:
      access-logger:
        enabled: true
        exclusions:
          - ^/health(?:/.*)?$
  router:
    static-resources:
      docs:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /docs/**
      openapi:
        paths: classpath:META-INF/swagger
        mapping: /docs/spec/**

rabbitmq:
  exchanges:
    orders: orders
  queues:
    order-completed: order-subscriptions.order-completed
  routing-keys:
    order-completed: order.completed

webhooks:
  order-completed:
    url: ${ORDER_COMPLETED_WEBHOOK_URL}
